### ISSUE TITLE
Excel Template Issues

### ISSUE THREAD

**Issue by LanceMcCarthy** [LanceMcCarthy/MvpApi#10]
There is an issue with the Data Validation and cascading drop down lists. [Download the Excel doc from this page in the repo (click the "Download" button)](https://github.com/LanceMcCarthy/MvpApi/blob/master/BulkUploadTemplate.xlsx).

To better explain the problem, I've recorded a short video that shows the issue and explains when it works and when it doesn't work.

## Issue 1

[Watch this 90 Second video of the issue](https://www.screencast.com/t/3hszQ742sE)

My suspicion is the issue is because the value has a space in it, but the reference list title has underscores.

Ex.

- "Windows Development" is the required field
- "Windows_Development" is the Named list Excel requires (no sapces allowed)

## Issue 2
When a selection is made in the first row, all other rows are stuck to that sublist.

You can download and try the Excel document for yourself

**Comment by dsdalg** [comment]
Change your DV formula to refer to the adjacent cell, instead of the entire column, and use the SUBSTITUTE function to replace the spaces with underscores:
=INDIRECT(SUBSTITUTE(B1," ","_"))
There's another example on my website:
http://www.contextures.com/xlDataVal02.html#TwoWord

**Comment by LanceMcCarthy** [comment]
Fantastic! Thanks @dsdalg

**Comment by dsdalg** [comment]
Your welcome! And you could set up a named table, with one or two rows set up, and it will expand automatically, as you enter data. 
To do that, select any cell in your list, and on the Home tab, click Format as table.
Click on the style that you want, then click OK
Excel will automatically add headings, which you can change, if you want to
Then, delete the rows from right below that, to the end of the worksheet, to get rid of all the extra DV that is in there.

**Comment by LanceMcCarthy** [comment]
Closing this as the excel feature is permanently on hold as the in-app form is much faster than using Excel doc
