### ISSUE TITLE
MVP API Fetch Failure

### ISSUE THREAD

**Issue by LanceMcCarthy** [LanceMcCarthy/MvpApi#104]
As of June 25, 2020. The API is no longer returning records or profile even though the user is signed in.

Weirdly enough, the Online Identities is still working, which verifies that there is nothing wrong with the API key or my authorization for the API.

![image](https://user-images.githubusercontent.com/3520532/85792617-cc614b00-b701-11ea-918e-c7c6413e573c.png)

**Comment by sthewissen** [comment]
Is this still happening for you? I'm getting data just fine. I get some intermittent oddities now and then, but I've grown used of those.

**Comment by LanceMcCarthy** [comment]
There's definitely something going on with the api services. At first I was worried my token was canceled, but it wouldn't have allowed the fetch of some data. This looks to be like a partial outage of some services (maybe 1 or 2 databases).

I haven't had a chance to actually look at the traffic yet, but if it's still a problem tomorrow morning, I'll reach out to the api team.

**Comment by LanceMcCarthy** [comment]
I double checked the API system and nothing there appears to be any different (i.e. cancelled token/subscription)

![image](https://user-images.githubusercontent.com/3520532/86255464-255b3400-bb85-11ea-9ddf-f677e1b6b786.png)

I will gather direct HTTP response details and report it to the API team.

**Comment by LanceMcCarthy** [comment]
The problem was likely related to renewal cycle and database updates. everything is up and running again,

![image](https://user-images.githubusercontent.com/3520532/86360899-04f0af80-bc41-11ea-9a4a-3217e5071ef6.png)

I did notice that some of the categories appeared to have changed. I opened a new issue to investigate and validate https://github.com/LanceMcCarthy/MvpApi/issues/105
