### ISSUE TITLE
When Visibility is set to Microsoft

### ISSUE THREAD

**Issue by JM2K69** [LanceMcCarthy/MvpApi#204]
When Visibility is set to Microsoft only your contribution in application aren't visible ?
![image](https://user-images.githubusercontent.com/17923944/155114026-3da6ba2e-3930-4292-9eff-b08120b19ecc.png)

Does it seems normal ?

**Comment by LanceMcCarthy** [comment]
You should see all contributions regardless of the value set for Visibility.

Maybe something went wrong with the fetch, try the Refresh button and let me know how it goes.

PS you can also go to the Settings page and click the Export button. That will give you the raw json the app gets from the MVP API, which tell us for sure if you're getting data

**Comment by JM2K69** [comment]
When I click on Refresh  it says I load 50 events and after I had nothing appear in the datagrid I have only at the bottom 18 items on 18 , but when I Export all my contrib it works.

**Comment by LanceMcCarthy** [comment]
Okay, so this is likely a bug due to the number of items being less than the batch size. I'll investigate asap, thanks for reporting this!

**Comment by JM2K69** [comment]
Does it find all contribs or just for the date defined for teh renew process ?

**Comment by LanceMcCarthy** [comment]
Okay, so this is likely a bug due to the number of items being less than the batch size. I'll investigate asap, thanks for reporting this!

**Comment by LanceMcCarthy** [comment]
It finds all the contributions in your history. Do you have more than 18?

**Comment by LanceMcCarthy** [comment]
Also, this issue doesn't prevent you from uploading. It's just a matter of 18 being less than 50 (the batch fetch size), I have a bug in there that only rears its ugly head if there is only one batch

**Comment by LanceMcCarthy** [comment]
@JM2K69 Can you send me an email to lance@dvlup.com so I can add you to the Beta flight? This will let you get the new version of the app without waiting 3-5 days for each release to pass certification.

the only thing I need from you is the Microsoft Account email address that you use for the Microsoft Store (send it in the email instead of this public-facing thread).

**Comment by LanceMcCarthy** [comment]
There is an updated version available that allows you to change the size of the fetches. Can you try with the fetch size set to 10 or 25? This has fixed the problem for someone else who was experiencing a similar issue.

Here's how to change it:

1. Open the app, stay on the Home page
2. Open the AppBar menu with "..." and then select the "Batch Size" button
3. The default value is set to 50, change it to 10

Once the change happens, it will refresh and take smaller batches per fetch

**Comment by JM2K69** [comment]
It work's thank you.
