### ISSUE TITLE
Support multiple contribution areas

### ISSUE THREAD

**Issue by onovotny** [LanceMcCarthy/MvpApi#48]
The MVP site now allows adding contributions and tagging them with multiple contribution areas. Would be great if the app could support that too.

**Comment by LanceMcCarthy** [comment]
Almost done adding this! I'll try to get it out by the end of the weekend.

**Comment by LanceMcCarthy** [comment]
I just wanted to leave this here as a reminder of how some things should be easier than they actually are...

![image](https://user-images.githubusercontent.com/3520532/45901749-088bad00-bdb2-11e8-8ce0-42686e68bcbc.png)

**Comment by LanceMcCarthy** [comment]
Completed first successful test for this in the https://github.com/LanceMcCarthy/MvpApi/tree/multiple-categories branch.

The feature is implemented on the Contribution Details page (where you can edit an existing contribution).

Here's a video of it in action https://twitter.com/lancewmccarthy/status/1043250453948129281

**Comment by LanceMcCarthy** [comment]
This is ready to use in the latest commit https://github.com/LanceMcCarthy/MvpApi/commit/88731d9edbb9635e6c441bc90a7c5fb4e37b44a7 

Small Issue Remaining
When examining an existing contribution, the number of additional contributions still shows and it's saved property, they're just not pre-selected in the Flyout ListView. This should be fixed tomorrow once I debug my cusotm attached property for Two-Way SelectedItems binding.

**Comment by LanceMcCarthy** [comment]
The bug appears to be unavoidable, I have redesigned the way you edit Additional Areas and will submit the update in this state. If the underlying problem with multiple selection is determined, I'll update again.

**Comment by LanceMcCarthy** [comment]
Released in v1.6:

- It will have an initial 25% staged roll out to make sure there are no major problems.
- If you manually check for updates, or use direct URL, you will get 1.6

**Comment by LanceMcCarthy** [comment]
https://www.microsoft.com/store/productId/9NRXNX3WLH77
