### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JeffreySu** [LanceMcCarthy/MvpApi#75]
I added about 8 contributions into Pending Uploads list , then click 
![image](https://user-images.githubusercontent.com/2281927/51105245-76595a00-1823-11e9-95a5-7010412161a7.png) button, it showed me **Object reference not set to an instance of an object** error for each item.

When I want to switch to home page, it alert me all the items will not be saved.

So I clicked the 
![image](https://user-images.githubusercontent.com/2281927/51105360-c0424000-1823-11e9-9a5b-51c9b16474cd.png) button for help, but when I go back to the **Add Contributions** page, all items gone.

**Comment by LanceMcCarthy** [comment]
Hi Jeffrey, thank you for reporting this. 

This could have been a false error warning because some of the items were edited after being added to the queue or a partially completed one. 

Did everything show up in the DataGrid after it navigated back to Home or were you missing an item?

**Comment by JeffreySu** [comment]
After I go back to home page from the help page, all records were disappeared, and even I couldn't load my Profile information. So I closed the App and restarted, then I can see the information as before, but Add Contribution cached items.

So I have to rearrange the content to upload again.

**Comment by LanceMcCarthy** [comment]
Okay.I'll look into it today. 

Those items should have been uploaded because the API confirms an item is saved before it tur a green. 

If it wasn't saved, it turns red and you stay on the Add Contributions page. 

Can you confirm you're using the latest version of the app 1.8.2.0

**Comment by LanceMcCarthy** [comment]
I may have found the underlying problem here. The API has changed its routes and you got caught in the middle of the change.

This was discovered and addressed in #76, I'm pushing out an update ASAP.

**Comment by JeffreySu** [comment]
My app version is the latest one in that time.

**Comment by LanceMcCarthy** [comment]
I found the fix! It will be in 1.9.1 when it goes live over the course of the night.

There are some new requirements for some category types. The app will now show you the exact error from the API service, which will tell you what part of the details was missing or wrong.

**Comment by JeffreySu** [comment]
Great!
